[package]
name = "foo"
version = "0.1.0"
edition = "2021"

[dependencies]
ocaml = { git = "https://github.com/zshipko/ocaml-rs" }

[build-dependencies]
cc = { version = "1" }
ocaml-build = { git = "https://github.com/zshipko/ocaml-rs", features = [
  "dune"
] }
